site_name: playwright-drupal
site_url: https://lullabot.github.io/playwright-drupal/
docs_dir: docs
site_dir: site

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
  features:
    - navigation.tabs
    - navigation.top

extra:
  version:
    provider: mike

nav:
  - Getting Started: getting-started.md
  - Writing Tests: writing-tests.md
  - Visual Comparisons: visual-comparisons.md
  - Configuration: configuration.md
  - GitHub Actions & Accessibility: github-actions.md
  - Development: development.md
