name: Conventional Commits

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint-pr-title:
    name: Validate PR Title
    runs-on: ubuntu-24.04
    steps:
      - name: Check PR title
        uses: amannn/action-semantic-pull-request@e32d7e603df1aa1ba07e981f2a23455dee596825 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint-commits:
    name: Validate Commits
    runs-on: ubuntu-24.04
    steps:
      - name: Check commit messages
        uses: webiny/action-conventional-commits@faccb24fc2550dd15c0390d944379d2d8ed9690e # v1.3.1
