name: Rebase

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    if: >-
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/rebase') &&
      (
        github.event.comment.author_association == 'OWNER' ||
        github.event.comment.author_association == 'MEMBER' ||
        github.event.comment.author_association == 'COLLABORATOR'
      )
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.REBASE_APP_ID }}
          private-key: ${{ secrets.REBASE_PRIVATE_KEY }}
      - name: Rebase PR branch
        uses: deviantintegral/rebase@0af71d3f8ec5bb2f8636e2f932268d3a64872bba
        with:
          token: ${{ steps.app-token.outputs.token }}
          rebase-options: '--no-keep-empty'
          incremental-push: true
